// flow-typed signature: 6f4c721343e1263436ace075ebaac0b3
// flow-typed version: <<STUB>>/dom-css_v^2.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'dom-css/index' {
  declare module.exports: $Exports<'dom-css'>;
}
declare module 'dom-css/index.js' {
  declare module.exports: $Exports<'dom-css'>;
}
