// flow-typed signature: 0cca82f3b2c9c0803a682044532803ec
// flow-typed version: <<STUB>>/electron-icon-maker_v^0.0.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-icon-maker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-icon-maker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-icon-maker/index' {
  declare module.exports: $Exports<'electron-icon-maker'>;
}
declare module 'electron-icon-maker/index.js' {
  declare module.exports: $Exports<'electron-icon-maker'>;
}
