// flow-typed signature: 84fe954f3b758b5aafa6f1c87754cb67
// flow-typed version: <<STUB>>/number-separator_v^2.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'number-separator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'number-separator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'number-separator/src/index' {
  declare module.exports: any;
}

declare module 'number-separator/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'number-separator/src/index.js' {
  declare module.exports: $Exports<'number-separator/src/index'>;
}
declare module 'number-separator/src/index.test.js' {
  declare module.exports: $Exports<'number-separator/src/index.test'>;
}
