// flow-typed signature: 1f099a4a29ba545b9e0e55cb21ef1703
// flow-typed version: <<STUB>>/tronweb_v^2.1.14/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tronweb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tronweb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tronweb/dist/TronWeb' {
  declare module.exports: any;
}

declare module 'tronweb/dist/TronWeb.node' {
  declare module.exports: any;
}

declare module 'tronweb/examples/browser/demo' {
  declare module.exports: any;
}

declare module 'tronweb/examples/server/index' {
  declare module.exports: any;
}

declare module 'tronweb/karma.conf' {
  declare module.exports: any;
}

declare module 'tronweb/scripts/pre-push' {
  declare module.exports: any;
}

declare module 'tronweb/scripts/test-browser' {
  declare module.exports: any;
}

declare module 'tronweb/scripts/test-node' {
  declare module.exports: any;
}

declare module 'tronweb/src/index' {
  declare module.exports: any;
}

declare module 'tronweb/src/lib/contract/index' {
  declare module.exports: any;
}

declare module 'tronweb/src/lib/contract/method' {
  declare module.exports: any;
}

declare module 'tronweb/src/lib/providers/HttpProvider' {
  declare module.exports: any;
}

declare module 'tronweb/src/lib/providers/index' {
  declare module.exports: any;
}

declare module 'tronweb/src/lib/transactionBuilder' {
  declare module.exports: any;
}

declare module 'tronweb/src/lib/trx' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/abi' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/accounts' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/address' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/base58' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/base64' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/bytes' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/code' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/crypto' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/help' {
  declare module.exports: any;
}

declare module 'tronweb/src/utils/index' {
  declare module.exports: any;
}

declare module 'tronweb/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tronweb/dist/TronWeb.js' {
  declare module.exports: $Exports<'tronweb/dist/TronWeb'>;
}
declare module 'tronweb/dist/TronWeb.node.js' {
  declare module.exports: $Exports<'tronweb/dist/TronWeb.node'>;
}
declare module 'tronweb/examples/browser/demo.js' {
  declare module.exports: $Exports<'tronweb/examples/browser/demo'>;
}
declare module 'tronweb/examples/server/index.js' {
  declare module.exports: $Exports<'tronweb/examples/server/index'>;
}
declare module 'tronweb/karma.conf.js' {
  declare module.exports: $Exports<'tronweb/karma.conf'>;
}
declare module 'tronweb/scripts/pre-push.js' {
  declare module.exports: $Exports<'tronweb/scripts/pre-push'>;
}
declare module 'tronweb/scripts/test-browser.js' {
  declare module.exports: $Exports<'tronweb/scripts/test-browser'>;
}
declare module 'tronweb/scripts/test-node.js' {
  declare module.exports: $Exports<'tronweb/scripts/test-node'>;
}
declare module 'tronweb/src/index.js' {
  declare module.exports: $Exports<'tronweb/src/index'>;
}
declare module 'tronweb/src/lib/contract/index.js' {
  declare module.exports: $Exports<'tronweb/src/lib/contract/index'>;
}
declare module 'tronweb/src/lib/contract/method.js' {
  declare module.exports: $Exports<'tronweb/src/lib/contract/method'>;
}
declare module 'tronweb/src/lib/providers/HttpProvider.js' {
  declare module.exports: $Exports<'tronweb/src/lib/providers/HttpProvider'>;
}
declare module 'tronweb/src/lib/providers/index.js' {
  declare module.exports: $Exports<'tronweb/src/lib/providers/index'>;
}
declare module 'tronweb/src/lib/transactionBuilder.js' {
  declare module.exports: $Exports<'tronweb/src/lib/transactionBuilder'>;
}
declare module 'tronweb/src/lib/trx.js' {
  declare module.exports: $Exports<'tronweb/src/lib/trx'>;
}
declare module 'tronweb/src/utils/abi.js' {
  declare module.exports: $Exports<'tronweb/src/utils/abi'>;
}
declare module 'tronweb/src/utils/accounts.js' {
  declare module.exports: $Exports<'tronweb/src/utils/accounts'>;
}
declare module 'tronweb/src/utils/address.js' {
  declare module.exports: $Exports<'tronweb/src/utils/address'>;
}
declare module 'tronweb/src/utils/base58.js' {
  declare module.exports: $Exports<'tronweb/src/utils/base58'>;
}
declare module 'tronweb/src/utils/base64.js' {
  declare module.exports: $Exports<'tronweb/src/utils/base64'>;
}
declare module 'tronweb/src/utils/bytes.js' {
  declare module.exports: $Exports<'tronweb/src/utils/bytes'>;
}
declare module 'tronweb/src/utils/code.js' {
  declare module.exports: $Exports<'tronweb/src/utils/code'>;
}
declare module 'tronweb/src/utils/crypto.js' {
  declare module.exports: $Exports<'tronweb/src/utils/crypto'>;
}
declare module 'tronweb/src/utils/help.js' {
  declare module.exports: $Exports<'tronweb/src/utils/help'>;
}
declare module 'tronweb/src/utils/index.js' {
  declare module.exports: $Exports<'tronweb/src/utils/index'>;
}
declare module 'tronweb/webpack.config.js' {
  declare module.exports: $Exports<'tronweb/webpack.config'>;
}
